complete -c santi020k-terminal -f
complete -c santi020k-terminal -n '__fish_use_subcommand' -a 'install update doctor preset colors status preview migrate uninstall version help'
complete -c santi020k-terminal -n '__fish_seen_subcommand_from preview' -a 'dark light'
complete -c santi020k-terminal -n '__fish_seen_subcommand_from preset; and not __fish_seen_subcommand_from list current use' -a 'list current use'
complete -c santi020k-terminal -n '__fish_seen_subcommand_from use' -a 'rich portable minimal'
complete -c santi020k-terminal -n '__fish_seen_subcommand_from colors; and not __fish_seen_subcommand_from list path install' -a 'list path install'
complete -c santi020k-terminal -n '__fish_seen_subcommand_from path install' -a 'iterm2 ghostty kitty wezterm alacritty windows-terminal'
complete -c santi020k-terminal -n '__fish_seen_subcommand_from iterm2 ghostty kitty wezterm alacritty windows-terminal' -a 'dark light'
complete -c santi020k-terminal -n '__fish_seen_subcommand_from doctor' -l fix -d 'Repair missing dependencies and configuration'
complete -c santi020k-terminal -n '__fish_seen_subcommand_from doctor; and __fish_contains_opt fix' -l yes -d 'Confirm dependency installation'
