name: Issue Assignment

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  auto-assign:
    name: Assign maintainer
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Auto-assign issue
        uses: pozil/auto-assign-issue@v2
        with:
          assignees: santi020k
          numOfAssignee: 1
          allowSelfAssign: true

